"""Persistent store/category profiles for the universal upload template."""

from __future__ import annotations

import json
import os
import re
from copy import deepcopy

import yaml
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter


SKILL_DIR = os.path.dirname(os.path.abspath(__file__))
PROFILE_FILE = os.path.join(SKILL_DIR, "store_profiles.yaml")
DEFAULT_PROFILE_FILE = os.path.join(SKILL_DIR, "store_profiles.defaults.yaml")

# Product values are generated by the processing pipeline and must never be
# replaced by template/profile defaults.
DYNAMIC_COLUMNS = {
    "A", "E", "F", "G", "H", "I", "K", "L", "M", "O", "P",
    "Q", "R", "S", "T", "W", "X", "Y", "Z", "AA", "AB",
}
STORE_COLUMNS = {"C", "D", "AE", "AF", "AG", "AH", "AI"}
CATEGORY_COLUMNS = {
    "J", "AC", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS",
    "AT", "AU", "AV", "AW", "AX", "AY", "AZ", "BC", "BE", "BF",
    "BG", "BH", "BI", "BJ", "BL",
}
COMMON_COLUMNS = {
    "B", "N", "U", "V", "AD", "AJ", "AK", "BA", "BB", "BD", "BK",
}
CONFIGURABLE_COLUMNS = STORE_COLUMNS | CATEGORY_COLUMNS | COMMON_COLUMNS
REQUIRED_STORE_COLUMNS = ("C", "D", "AE", "AF", "AG", "AH", "AI")
REQUIRED_CATEGORY_COLUMNS = ("AL", "AM")


def _clean_fields(fields):
    result = {}
    if not isinstance(fields, dict):
        return result
    for key, value in fields.items():
        column = str(key or "").strip().upper()
        if column not in CONFIGURABLE_COLUMNS or value is None or value == "":
            continue
        if isinstance(value, float) and value.is_integer():
            value = str(int(value))
        elif isinstance(value, (int, float)):
            value = str(value)
        result[column] = value
    return result


def _clean_aliases(values):
    if isinstance(values, str):
        values = re.split(r"[,，;；\n]+", values)
    if not isinstance(values, list):
        return []
    result = []
    for value in values:
        value = str(value or "").strip()
        if value and value not in result:
            result.append(value)
    return result


def normalize_profiles(data):
    data = data if isinstance(data, dict) else {}
    result = {
        "version": int(data.get("version", 1) or 1),
        "global_fields": _clean_fields(data.get("global_fields", {})),
        "stores": [],
    }
    seen_stores = set()
    for raw_store in data.get("stores", []):
        if not isinstance(raw_store, dict):
            continue
        store_id = str(raw_store.get("id", "")).strip()
        if not store_id or store_id in seen_stores:
            continue
        seen_stores.add(store_id)
        store = {
            "id": store_id,
            "name": str(raw_store.get("name") or store_id).strip(),
            "aliases": _clean_aliases(raw_store.get("aliases", [])),
            "fields": _clean_fields(raw_store.get("fields", {})),
            "categories": [],
        }
        seen_categories = set()
        for raw_category in raw_store.get("categories", []):
            if not isinstance(raw_category, dict):
                continue
            category_id = str(raw_category.get("id", "")).strip()
            if not category_id or category_id in seen_categories:
                continue
            seen_categories.add(category_id)
            store["categories"].append({
                "id": category_id,
                "name": str(raw_category.get("name") or category_id).strip(),
                "fields": _clean_fields(raw_category.get("fields", {})),
            })
        result["stores"].append(store)
    return result


def load_store_profiles(path=None):
    profile_path = path or PROFILE_FILE
    if not os.path.isfile(profile_path) and path is None:
        profile_path = DEFAULT_PROFILE_FILE
    if not os.path.isfile(profile_path):
        return normalize_profiles({})
    try:
        with open(profile_path, "r", encoding="utf-8") as handle:
            return normalize_profiles(yaml.safe_load(handle))
    except Exception:
        return normalize_profiles({})


def save_store_profiles(data, path=None):
    path = path or PROFILE_FILE
    clean = normalize_profiles(data)
    with open(path, "w", encoding="utf-8") as handle:
        yaml.safe_dump(clean, handle, allow_unicode=True, sort_keys=False)
    return clean


def find_store(data, store_id):
    if not isinstance(data, dict):
        return None
    for store in data.get("stores", []):
        if store["id"] == str(store_id or ""):
            return store
    return None


def find_category(store, category_id):
    if not isinstance(store, dict):
        return None
    for category in store.get("categories", []):
        if category["id"] == str(category_id or ""):
            return category
    return None


def read_template_fixed_fields(template_path, row=8):
    workbook = load_workbook(template_path, read_only=True, data_only=False)
    sheet = workbook["NEW 일반상품"] if "NEW 일반상품" in workbook.sheetnames else workbook.active
    fields = {}
    for column_index in range(1, 67):
        column = get_column_letter(column_index)
        if column not in CONFIGURABLE_COLUMNS:
            continue
        value = sheet.cell(row=row, column=column_index).value
        if value is not None and value != "":
            fields[column] = value
    workbook.close()
    return fields


def resolve_fields(template_fields=None, store_id="", category_id="", data=None):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    result = _clean_fields(template_fields or {})
    result.update(data.get("global_fields", {}))
    store = find_store(data, store_id)
    if store:
        result.update(store.get("fields", {}))
        category = find_category(store, category_id)
        if category:
            result.update(category.get("fields", {}))
    return result


def category_fields(store_id, category_id, data=None):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    store = find_store(data, store_id)
    category = find_category(store, category_id)
    return dict(category.get("fields", {})) if category else {}


def category_hint(store_id, category_id, data=None):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    category = find_category(find_store(data, store_id), category_id)
    if not category:
        return ""
    return category.get("name", "")


def validate_profile(store_id, category_id, data=None):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    store = find_store(data, store_id)
    if not store:
        return ["未选择有效店铺"]
    merged = dict(data.get("global_fields", {}))
    merged.update(store.get("fields", {}))
    missing = [column for column in REQUIRED_STORE_COLUMNS if not merged.get(column)]
    category = find_category(store, category_id)
    if not category:
        return ["未选择有效店铺类目"] + [f"店铺字段 {c} 为空" for c in missing]
    merged.update(category.get("fields", {}))
    missing.extend(column for column in REQUIRED_CATEGORY_COLUMNS if not merged.get(column))
    return [f"固定字段 {column} 为空" for column in missing]


def validate_store_profile(store_id, data=None):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    store = find_store(data, store_id)
    if not store:
        return ["未选择有效店铺"]
    merged = dict(data.get("global_fields", {}))
    merged.update(store.get("fields", {}))
    errors = [f"店铺固定字段 {column} 为空" for column in REQUIRED_STORE_COLUMNS
              if not merged.get(column)]
    categories = store.get("categories", [])
    if not categories:
        errors.append("该店铺尚未配置任何类目")
    for category in categories:
        category_merged = dict(merged)
        category_merged.update(category.get("fields", {}))
        for column in REQUIRED_CATEGORY_COLUMNS:
            if not category_merged.get(column):
                errors.append(f"类目 {category['name']} 的 {column} 为空")
    return errors


def _normalized_text(value):
    return re.sub(r"[^0-9a-z\u3400-\u9fff\uac00-\ud7a3]+", "", str(value or "").lower())


def _alias_score(text, aliases):
    text = _normalized_text(text)
    best = 0
    for alias in aliases:
        normalized = _normalized_text(alias)
        if normalized and normalized in text:
            best = max(best, len(normalized))
    return best


def _find_category_by_id_or_name(store, value):
    category = find_category(store, value)
    if category:
        return category
    normalized = _normalized_text(value)
    if not normalized:
        return None
    matches = [
        candidate for candidate in (store or {}).get("categories", [])
        if _normalized_text(candidate.get("name", "")) == normalized
    ]
    return matches[0] if len(matches) == 1 else None


def read_source_context(source_path, sample_rows=6):
    """Read compact workbook metadata for profile inference without loading all rows."""
    if not source_path or not os.path.isfile(source_path):
        return {"sheet_name": "", "headers": [], "rows": []}
    try:
        workbook = load_workbook(source_path, read_only=True, data_only=True)
        sheet = workbook.active
        rows = sheet.iter_rows(min_row=1, max_row=sample_rows + 1, values_only=True)
        first = next(rows, ())
        headers = [str(value).strip() for value in first if value not in (None, "")]
        samples = []
        for row in rows:
            selected = {}
            for index, label in ((0, "parent_sku"), (2, "title"), (4, "tag"),
                                 (5, "brand"), (11, "source_url")):
                if index < len(row) and row[index] not in (None, ""):
                    selected[label] = str(row[index])[:300]
            if selected:
                samples.append(selected)
        result = {"sheet_name": sheet.title, "headers": headers[:100], "rows": samples}
        workbook.close()
        return result
    except Exception:
        return {"sheet_name": "", "headers": [], "rows": []}


def deterministic_suggestion(source_path, products, data=None):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    filename = os.path.basename(source_path or "")
    source_context = read_source_context(source_path)
    samples = list(products or [])[:8]
    product_text = " ".join(
        f"{getattr(product, 'title', '')} {getattr(product, 'tag', '')} "
        f"{getattr(product, 'brand', '')}"
        for product in samples
    )

    store_scores = []
    for store in data.get("stores", []):
        aliases = [store["id"], store["name"], *store.get("aliases", [])]
        score = _alias_score(filename, aliases) * 100
        score += _alias_score(json.dumps(source_context, ensure_ascii=False), aliases)
        store_scores.append((score, store))
    store_scores.sort(key=lambda item: item[0], reverse=True)
    best_store_score = store_scores[0][0] if store_scores else 0
    store = store_scores[0][1] if best_store_score > 0 else None
    if not store and len(data.get("stores", [])) == 1:
        store = data["stores"][0]

    category = None
    if store:
        category_scores = []
        for candidate in store.get("categories", []):
            names = [candidate["id"], candidate["name"]]
            score = _alias_score(filename, names) * 100
            score += _alias_score(product_text, names)
            category_scores.append((score, candidate))
        category_scores.sort(key=lambda item: item[0], reverse=True)
        if category_scores and category_scores[0][0] > 0:
            category = category_scores[0][1]
        elif len(store.get("categories", [])) == 1:
            category = store["categories"][0]

    evidence = []
    if store:
        evidence.append(f"文件名/别名匹配店铺 {store['name']}")
    if category:
        evidence.append(f"文件名或商品字段匹配类目 {category['name']}")
    return {
        "store_id": store["id"] if store else "",
        "category_id": category["id"] if category else "",
        "confidence": 1.0 if best_store_score > 0 else (0.5 if store else 0.0),
        "evidence": evidence,
        "method": "rule",
    }


def _parse_json_object(text):
    match = re.search(r"\{.*\}", str(text or ""), re.S)
    if not match:
        return {}
    try:
        value = json.loads(match.group(0))
        return value if isinstance(value, dict) else {}
    except Exception:
        return {}


def suggest_source_profile(source_path, products, data=None, use_ai=True):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    rule_result = deterministic_suggestion(source_path, products, data)
    if not use_ai or (rule_result["store_id"] and rule_result["category_id"]):
        return rule_result
    if not data.get("stores"):
        return rule_result

    candidates = []
    for store in data["stores"]:
        candidates.append({
            "store_id": store["id"],
            "store_name": store["name"],
            "aliases": store.get("aliases", []),
            "categories": [
                {
                    "category_id": category["id"],
                    "name": category["name"],
                }
                for category in store.get("categories", [])
            ],
        })
    samples = [
        {
            "title": getattr(product, "title", ""),
            "tag": getattr(product, "tag", ""),
            "brand": getattr(product, "brand", ""),
            "source_url": getattr(product, "url", ""),
        }
        for product in list(products or [])[:6]
    ]
    source_context = read_source_context(source_path)
    prompt = (
        "你是上传表配置选择器。只能从候选列表中选择，严禁编造店铺、类目或代码。"
        "店铺通常只能由文件名或候选别名判断；没有证据时 store_id 必须为空。"
        "只输出一个 JSON 对象，字段为 store_id、category_id、confidence、evidence。\n\n"
        f"采集表文件名：{os.path.basename(source_path or '')}\n"
        f"工作表、表头和原始字段样本：{json.dumps(source_context, ensure_ascii=False)}\n"
        f"商品样本：{json.dumps(samples, ensure_ascii=False)}\n"
        f"候选配置：{json.dumps(candidates, ensure_ascii=False)}"
    )
    try:
        from api_client import deepseek_chat

        parsed = _parse_json_object(deepseek_chat(prompt, max_tokens=300, temp=0.1))
    except Exception as exc:
        result = dict(rule_result)
        result["error"] = str(exc)
        return result

    store_id = str(parsed.get("store_id", "") or "")
    category_id = str(parsed.get("category_id", "") or "")
    store = find_store(data, store_id)
    category = find_category(store, category_id)
    if not store:
        store_id = rule_result["store_id"]
        store = find_store(data, store_id)
    if not category or (store and category not in store.get("categories", [])):
        category_id = rule_result["category_id"]
    try:
        confidence = max(0.0, min(1.0, float(parsed.get("confidence", 0))))
    except (TypeError, ValueError):
        confidence = 0.0
    evidence = parsed.get("evidence", [])
    if not isinstance(evidence, list):
        evidence = [str(evidence)] if evidence else []
    return {
        "store_id": store_id,
        "category_id": category_id,
        "confidence": confidence,
        "evidence": [str(item) for item in evidence[:4]],
        "method": "deepseek",
    }


def best_category_for_text(store_id, text, data=None):
    data = normalize_profiles(data if data is not None else load_store_profiles())
    store = find_store(data, store_id)
    if not store:
        return ""
    scored = []
    for category in store.get("categories", []):
        scored.append((_alias_score(text, [category["name"]]), category["id"]))
    scored.sort(reverse=True)
    return scored[0][1] if scored and scored[0][0] > 0 else ""


def match_store_category(store_id, product, category_path="", category_zh="",
                         data=None, use_ai=True):
    """Choose one saved AL/AM profile for a single product."""
    data = normalize_profiles(data if data is not None else load_store_profiles())
    store = find_store(data, store_id)
    if not store:
        return {"category_id": "", "confidence": 0.0, "method": "none",
                "evidence": ["未选择有效店铺"]}
    candidates = store.get("categories", [])
    if not candidates:
        return {"category_id": "", "confidence": 0.0, "method": "none",
                "evidence": ["店铺未配置类目"]}
    if len(candidates) == 1:
        return {"category_id": candidates[0]["id"], "confidence": 1.0,
                "method": "single", "evidence": ["店铺仅配置一个类目"]}

    subject_profile = getattr(product, "subject_profile", {}) or {}
    subject_identity = " ".join(
        str(subject_profile.get(key, "") or "").strip()
        for key in ("sold_object_ko", "sold_object_zh", "sold_object",
                    "buyer_receives", "primary_function")
    ).strip()
    generated_terms = []
    for key in ("category_terms_ko", "category_terms_zh"):
        values = subject_profile.get(key, [])
        if not isinstance(values, list):
            values = [values] if values else []
        generated_terms.extend(str(value or "").strip() for value in values if value)
    subject_identity = " ".join([subject_identity] + generated_terms).strip()
    if subject_identity:
        product_context = subject_identity
    else:
        product_context = " ".join((
            str(getattr(product, "title", "") or ""),
            str(getattr(product, "tag", "") or ""),
            str(getattr(product, "brand", "") or ""),
        ))
    text = " ".join((str(category_zh or ""), str(category_path or ""), product_context))
    scored = []
    for category in candidates:
        scored.append((_alias_score(text, [category["name"]]), category))
    scored.sort(key=lambda item: item[0], reverse=True)
    top_score = scored[0][0]
    second_score = scored[1][0] if len(scored) > 1 else 0
    if top_score > 0 and (second_score == 0 or top_score > second_score * 2):
        category = scored[0][1]
        return {"category_id": category["id"], "confidence": 0.95,
                "method": "rule", "evidence": [f"字段关键词匹配 {category['name']}"]}
    if not use_ai:
        return {"category_id": "", "confidence": 0.0, "method": "none",
                "evidence": ["关键词无法唯一确定店铺类目"]}

    prompt_candidates = [
        {
            "category_id": category["id"],
            "name": category["name"],
        }
        for category in candidates
    ]
    prompt = (
        "Classify the actual item the buyer receives. Do not classify an object that "
        "the sold item stores, supports, protects, connects to, fits, controls, or is "
        "shown with. The sold-item analysis is authoritative over noisy raw tags.\n"
        "你是店铺业务大类选择器。商品的韩国平台精确类目已经匹配完成，"
        "现在必须从候选店铺大类中选择最接近的一个，用于取得该店铺对应的 AL/AM。"
        "候选项是宽泛的业务大类，不要求与商品精确类目同名。"
        "即使没有完全对应的大类，也必须根据商品用途选择最接近的一项，category_id 禁止为空。"
        "category_id 必须原样复制候选项中的 category_id，不能填写类目名称。"
        "严禁编造候选池之外的 category_id 或代码。"
        "只输出 JSON：category_id、confidence、evidence。\n\n"
        f"售卖主体分析：{json.dumps(subject_profile, ensure_ascii=False)}\n"
        f"商品标题：{getattr(product, 'title', '')}\n"
        f"商品标签（可能含噪声）：{getattr(product, 'tag', '')}\n"
        f"匹配后的韩国类目：{category_path}\n"
        f"匹配后的中文类目：{category_zh}\n"
        f"候选店铺类目：{json.dumps(prompt_candidates, ensure_ascii=False)}"
    )
    deepseek_calls = 0
    try:
        from api_client import deepseek_chat

        parsed = _parse_json_object(deepseek_chat(prompt, max_tokens=240, temp=0.1))
        deepseek_calls += 1
    except Exception as exc:
        return {"category_id": "", "confidence": 0.0, "method": "deepseek",
                "evidence": [str(exc)], "error": str(exc), "deepseek_calls": deepseek_calls}
    category_id = str(parsed.get("category_id", "") or "")
    category = _find_category_by_id_or_name(store, category_id)
    if not category:
        repair_prompt = (
            "Use the sold-item analysis to classify the physical item the buyer receives, "
            "not a referenced or compatible object. "
            "上一次返回无效。现在必须从候选业务大类中选择且只能选择一个，禁止返回空值，"
            "禁止解释没有精确类目。category_id 必须原样复制候选项中的 category_id。"
            "只输出 JSON：category_id、confidence、evidence。\n\n"
            f"售卖主体分析：{json.dumps(subject_profile, ensure_ascii=False)}\n"
            f"商品标题：{getattr(product, 'title', '')}\n"
            f"商品标签（可能含噪声）：{getattr(product, 'tag', '')}\n"
            f"匹配后的韩国类目：{category_path}\n"
            f"匹配后的中文类目：{category_zh}\n"
            f"候选店铺大类：{json.dumps(prompt_candidates, ensure_ascii=False)}"
        )
        try:
            parsed = _parse_json_object(deepseek_chat(repair_prompt, max_tokens=180, temp=0.0))
            deepseek_calls += 1
            category_id = str(parsed.get("category_id", "") or "")
            category = _find_category_by_id_or_name(store, category_id)
        except Exception as exc:
            return {"category_id": "", "confidence": 0.0, "method": "deepseek",
                    "evidence": [str(exc)], "error": str(exc),
                    "deepseek_calls": deepseek_calls}
    category_id = category["id"] if category else ""
    try:
        confidence = max(0.0, min(1.0, float(parsed.get("confidence", 0))))
    except (TypeError, ValueError):
        confidence = 0.0
    evidence = parsed.get("evidence", [])
    if not isinstance(evidence, list):
        evidence = [str(evidence)] if evidence else []
    return {"category_id": category_id, "confidence": confidence,
            "method": "deepseek", "evidence": [str(item) for item in evidence[:3]],
            "deepseek_calls": deepseek_calls}


def _id_from_name(value, fallback_prefix, existing):
    match = re.search(r"T\d+", value or "", re.I)
    if match:
        base = match.group(0).lower()
    else:
        base = re.sub(r"[^0-9a-z]+", "_", str(value or "").lower()).strip("_")
    if not base:
        base = fallback_prefix
    result = base
    suffix = 2
    while result in existing:
        result = f"{base}_{suffix}"
        suffix += 1
    return result


def import_template_profile(template_path, data=None):
    data = normalize_profiles(deepcopy(data) if data is not None else load_store_profiles())
    stem = os.path.splitext(os.path.basename(template_path))[0]
    store_match = re.search(r"T\d+", stem, re.I)
    store_name = store_match.group(0).upper() if store_match else stem.split("-")[0]
    category_name = ""
    if "-" in stem:
        category_name = stem.split("-", 1)[1]
    category_name = re.sub(r"\(\d+\)$", "", category_name).strip() or "默认类目"

    store = None
    for candidate in data["stores"]:
        if _normalized_text(store_name) in {
            _normalized_text(candidate["id"]), _normalized_text(candidate["name"]),
            *(_normalized_text(alias) for alias in candidate.get("aliases", [])),
        }:
            store = candidate
            break
    if store is None:
        store_id = _id_from_name(store_name, "store", {item["id"] for item in data["stores"]})
        store = {"id": store_id, "name": store_name, "aliases": [store_name], "fields": {}, "categories": []}
        data["stores"].append(store)

    fields = read_template_fixed_fields(template_path)
    for column in COMMON_COLUMNS | STORE_COLUMNS:
        if column in fields:
            store["fields"][column] = fields[column]

    category = None
    for candidate in store["categories"]:
        names = [candidate["id"], candidate["name"]]
        if any(_normalized_text(name) == _normalized_text(category_name) for name in names):
            category = candidate
            break
    if category is None:
        existing = {item["id"] for item in store["categories"]}
        category_id = _id_from_name(category_name, "category", existing)
        category = {
            "id": category_id,
            "name": category_name,
            "fields": {},
        }
        store["categories"].append(category)
    for column in CATEGORY_COLUMNS:
        if column in fields:
            category["fields"][column] = fields[column]
    return normalize_profiles(data), store["id"], category["id"]
